<?php
/* @var $model InfoScreen_Model_Day */
$model = $this->model;
?>

<?php if(!$this->ajax): ?>
    <?php
    echo $this->partial('index/form.phtml', array(
        'date'       => $model->getDate(),
        'mode'       => 'day',
        'submitText' => 'Raumbelegung laden'
    ));
    ?>

    <section id="results">
<?php endif; ?>

    <?php $title = strftime('%A, %d.%m.%Y', strtotime($model->getDate())) ?>
    <h1 id="pagetitle" class="<?php if($model->hasData()) echo "results"; else echo "noresults"; ?>">
         <a href="<?php echo InfoScreen_Model_Request::factory()->getFilterUrl(); ?>" title="Permanentlink auf diese Filterkriterien"><?php echo $title; ?></a>
    </h1>

    <?php $filterUrl = InfoScreen_Model_Request::factory()->getFilterUrl(false); ?>
    <div id="date-prev" class="pager">
        <?php $datePrev = $this->dayPager($model->getDate(), 'prev'); ?>
        <a title="vorheriger Tag" rel="<?php echo $datePrev ?>" href="<?php echo $this->baseUrl(); ?>/day/date/<?php echo $datePrev ?><?php echo $filterUrl ?>"><span>&laquo; zurück</span></a>
    </div>
    <div id="date-next" class="pager">
        <?php $dateNext = $this->dayPager($model->getDate(), 'next'); ?>
        <a title="nächster Tag" rel="<?php echo $dateNext ?>" href="<?php echo $this->baseUrl(); ?>/day/date/<?php echo $dateNext ?><?php echo $filterUrl ?>"><span>weiter &raquo;</span></a>
    </div>

    <?php if($model->hasData()): ?>
        <table id="resultTable" class="dataTable">
            <thead>
                <tr>
                    <th>Studiengang</th>
                    <th>Beschreibung</th>
                    <th>Gr.</th>
                    <th>Lektor</th>
                    <th>Raum</th>
                    <th>Beginn</th>
                    <th>Ende</th>
                    <th>Info</th>
                </tr>
            </thead>
            <tbody>
                <?php
                $i = 0;

                /* @var $lecture InfoScreen_Model_Lecture */
                foreach($model->getFilteredData() as $lecture):
                ?>
                    <?php $class = ($i++ % 2 == 0) ? 'even' : 'odd'; ?>
                    <tr class="<?php echo $class ?>">
                        <td class="course"><?php echo $this->filterLink('course', $lecture->course) ?></td>
                        <td class="description"><?php echo $lecture->description ?></td>
                        <td class="group"><?php echo $lecture->group ?></td>
                        <td class="lector"><?php echo $this->filterLink('lector', $lecture->lector) ?></td>
                        <td class="room"><?php echo $this->filterLink('room', $lecture->room) ?></td>
                        <td class="startTime time"><?php echo $lecture->startTime ?></td>
                        <td class="endTime time"><?php echo $lecture->endTime ?></td>
                        <td class="info"><?php echo $lecture->info ?></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    <?php else: ?>
        <p id="error">Für die angegebenen Filterkriterien gibt es keine Ergebnisse.</p>
    <?php endif; ?>

<?php if(!$this->ajax): ?>
</section>
<?php endif; ?>

<?php
if($this->ajax) {
    InfoScreen_Statistics::track($title);
}
?>