<?php
/* @var $model InfoScreen_Model_Day */
$model = $this->model;
?>

<?php if(!$this->ajax): ?>
<div id="header" class="daymode span-24">
      <?php
      echo $this->partial('index/form.phtml', array(
          'date'       => $model->getDate(),
          'mode'       => 'day',
          'submitText' => 'Raumbelegung laden'
      ));
      ?>
</div>

<div id="main" class="daymode span-24">
<?php endif; ?>

    <div id="dayPager">
        <?php $filterUrl = InfoScreen_Model_Request::factory()->getFilterUrl(false); ?>
        <div class="aleft span-12">
            <?php $datePrev = $this->dayPager($model->getDate(), 'prev'); ?>
            <a title="vorheriger Tag" rel="<?php echo $datePrev ?>" href="<?php echo $this->baseUrl(); ?>/day/date/<?php echo $datePrev ?><?php echo $filterUrl ?>">&laquo; zurück</a>
        </div>
        <div class="aright span-12 last">
            <?php $dateNext = $this->dayPager($model->getDate(), 'next'); ?>
            <a title="nächster Tag" rel="<?php echo $dateNext ?>" href="<?php echo $this->baseUrl(); ?>/day/date/<?php echo $dateNext ?><?php echo $filterUrl ?>">weiter &raquo;</a>
        </div>
    </div>

    <?php $this->title = strftime('%A, %d.%m.%Y', strtotime($model->getDate())) ?>
    <h2 id="pagetitle" class="<?php if($model->hasData()) echo "results"; else echo "noresults"; ?>">
         <?php echo $this->title; ?>
    </h2>

    <?php if($model->hasData()): ?>
    <table cellpadding='0' cellspacing='0' id="infoTable">
        <thead>
            <tr>
                <th>Studiengang</th>
                <th>Fach</th>
                <th>Gr.</th>
                <th>Lektor</th>
                <th>Raum</th>
                <th>Beginn</th>
                <th>Ende</th>
                <th>Info</th>
            </tr>
        </thead>
        <tbody>
            <?php
            /* @var $lecture InfoScreen_Model_Lecture */
            foreach($model->getFilteredData() as $lecture):
            ?>
            <tr>
                <td class="course"><?php echo $this->filterLink('course', $lecture->course) ?></td>
                <td class="description"><?php echo $lecture->description ?></td>
                <td class="group"><?php echo $lecture->group ?></td>
                <td class="lector"><?php echo $this->filterLink('lector', $lecture->lector) ?></td>
                <td class="room"><?php echo $this->filterLink('room', $lecture->room) ?></td>
                <td class="startTime time"><?php echo $lecture->startTime ?></td>
                <td class="endTime time"><?php echo $lecture->endTime ?></td>
                <td class="info"><?php echo $lecture->info ?></td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    <?php else: ?>
    <p id="error">Für die angegebenen Filterkriterien gibt es keine Ergebnisse.</p>
    <?php endif; ?>

<?php if(!$this->ajax): ?>
</div>
<?php endif; ?>

<?php
if($this->ajax && $this->config->frontend->piwik->enabled) {
    $t = new PiwikTracker($this->config->frontend->piwik->siteid, 'http://' . $this->config->frontend->piwik->baseurl);
    $t->doTrackPageView($this->title);
}
?>