
    <form id="filterform" class="clearfix" method="post" action="<?php echo $this->baseUrl() . '/' . $this->mode ?>">
        <div class="frm-date">
            <label for="sel-date">Datum</label>
            <input id="sel-date" class="datePickerWidget" name="date" value="<?php echo $this->date ?>">
        </div>

        <div class="frm-course">
            <label for="sel-course">Studiengang</label>
            <select id="sel-course" name="course">
                <?php foreach(InfoScreen_Model_List::getInstance('course')->getSelectData() as $course):?>
                <option<?php $this->checkSelected($course, 'course') ?>><?php echo $course ?></option>
                <?php endforeach; ?>
            </select>
        </div>

        <div class="frm-lector">
            <label for="sel-lector">Lektor</label>
            <select id="sel-lector" name="lector">
                <?php foreach(InfoScreen_Model_List::getInstance('lector')->getSelectData() as $lector):?>
                <option<?php $this->checkSelected($lector, 'lector') ?>><?php echo $lector ?></option>
                <?php endforeach; ?>
            </select>
        </div>

        <div class="frm-room">
            <label for="sel-room">Raum</label>
            <select id="sel-room" name="room">
                <?php foreach(InfoScreen_Model_List::getInstance('room')->getSelectData() as $room):?>
                <option<?php $this->checkSelected($room, 'room') ?>><?php echo $room ?></option>
                <?php endforeach; ?>
            </select>
        </div>

        <div class="frm-strict">
            <label for="chb-strict">Strict?</label>
            <input id="chb-strict" type="checkbox" name="strict"<?php echo InfoScreen_Model_Request::factory()->isStrict() ? ' checked="checked"' : '' ?>>
        </div>

        <div class="frm-submit">
            <input class="button medium red" id="input-submit" type="submit" name="submit" value="<?php echo $this->submitText ?>">
        </div>

        <div class="frm-reset">
            <a class="button medium blue" id="input-reset" href="<?php echo $this->baseUrl(); ?>/<?php echo $this->mode ?><?php echo InfoScreen_Model_Request::factory()->getDateUrl(); ?>">Filter zurücksetzen</a>
        </div>
    </form>