			<h2>Ergebnisse für <?php echo $this->date ?></h2>

			<?php if(count($this->appointments) > 0): ?>

			<table cellpadding='0' cellspacing='0' id="infoTable">
				<thead>
					<tr>
						<th>Studiengang</th>
						<th>Fach</th>
						<th>Lektor</th>
						<th>Raum</th>
						<th>Beginn</th>
						<th>Ende</th>
						<th>Info</th>			
					</tr>
				</thead>
				
				<tbody>
					<?php foreach($this->appointments as $a): ?>

					<tr>
						<td class="class"><?php $this->filterLink('class', $a['class']) ?></td>
						<td class="description"><?php echo $a['description'] ?></td>
						<td class="lector"><?php $this->filterLink('lector', $a['lector']) ?></td>
						<td class="room"><?php $this->filterLink('room', $a['room']) ?></td>
						<td class="startTime time"><?php echo $a['startTime'] ?></td>
						<td class="endTime time"><?php echo $a['endTime'] ?></td>
						<td class="info"><?php echo $a['info'] ?></td>
					</tr>

					<?php endforeach; ?>
				</tbody>
				
			</table>
			<?php else: ?>
			<p>Keine Ergebnisse.</p>
			<?php endif; ?>