<?php
/* @var $model InfoScreen_Model_Week */
$model = $this->model;
?>

<?php if(!$this->ajax): ?>
<div id="header" class="span-24">
    <form method="post" action="<?php echo $this->baseUrl() . '/week' ?>" id="filterform">
        <div class="column span-4">
            <label for="sel_date">Datum</label>
            <input id="sel_date" name="date" value="<?php echo $model->getStartDate() ?>" />
        </div>

        <div class="column span-4">
            <label for="sel_class">Studiengang</label>
            <select id="sel_class" name="class">
                    <?php foreach(InfoScreen_Model_List::getInstance('class')->getSelectData() as $class):?>
                    <option<?php $this->checkSelected($class, 'class') ?>><?php echo $class ?></option>
                    <?php endforeach; ?>
            </select>
        </div>

        <div class="column span-5">
            <label for="sel_lector">Lektor</label>
            <select id="sel_lector" name="lector">
                <?php foreach(InfoScreen_Model_List::getInstance('lector')->getSelectData() as $lector):?>
                <option<?php $this->checkSelected($lector, 'lector') ?>><?php echo $lector ?></option>
                <?php endforeach; ?>
            </select>
        </div>

        <div class="column span-2">
            <label for="sel_room">Raum</label>
            <select id="sel_room" name="room">
                <?php foreach(InfoScreen_Model_List::getInstance('room')->getSelectData() as $room):?>
                <option<?php $this->checkSelected($room, 'room') ?>><?php echo $room ?></option>
                <?php endforeach; ?>
            </select>
        </div>

        <div class="submitbox column prepend-1 span-4">
            <a id="input_reset" href="<?php echo $this->baseUrl(); ?>/week<?php echo InfoScreen_Controller_Request::getDateUrl(); ?>">Filter zurücksetzen</a>
        </div>

        <div class="submitbox column span-4 last">
            <input type="hidden" name="strict" value="<?php echo InfoScreen_Controller_Request::isStrictFiltering() ? 'true' : 'false' ?>" />
            <input id="input_submit" type="submit" name="submit" value="Übersicht laden" />
        </div>
    </form>
</div>

<div id="main" class="span-24">
<?php endif; ?>

    <div id="dayPager">
        <?php $filterUrl = InfoScreen_Controller_Request::getFilterUrl(false); ?>
        <div class="aleft span-12">
            <?php $datePrev = $this->weekPager($model->getStartDate(), 'prev'); ?>
            <a title="vorherige Woche" rel="<?php echo $datePrev ?>" href="<?php echo $this->baseUrl(); ?>/week/date/<?php echo $datePrev ?>/<?php echo $filterUrl ?>">&laquo; zurück</a>
        </div>
        <div class="aright span-12 last">
            <?php $dateNext = $this->weekPager($model->getStartDate(), 'next'); ?>
            <a title="nächste Woche" rel="<?php echo $dateNext ?>" href="<?php echo $this->baseUrl(); ?>/week/date/<?php echo $dateNext ?>/<?php echo $filterUrl ?>">weiter &raquo;</a>
        </div>
    </div>

    <?php $this->title = 'Woche ab ' . strftime('%A, %d.%m.%Y', strtotime($model->getStartDate())); ?>

<?php
$i = 0;

/* @var $day InfoScreen_Model_Day */
foreach($model->getData() as $day):
?>
    <?php $dayClass = ($i++ % 2 == 0) ? 'even' : 'odd'; ?>

    <div class="weekday <?php echo $dayClass ?>">
        <h3><a href="/day/date/<?php echo $day->getDate(); ?>"><?php echo strftime('%A, %d.%m.%Y', strtotime($day->getDate())); ?></a></h3>
        <?php if($day->hasData()): ?>

        <table class="appointmentTable">
            <?php
            $j = 0;

            /* @var $lecture InfoScreen_Model_Lecture */
            foreach($day->getFilteredData() as $lecture):
            ?>
                <?php $lectureClass = ($j++ % 2 == 0) ? 'even' : 'odd'; ?>

                <tr class="<?php echo $lectureClass ?>">
                    <td class="startTime time"><?php echo $lecture->startTime; ?></td>
                    <td class="endTime time"><?php echo $lecture->endTime; ?></td>
                    <td class="class"><?php echo $lecture->__get('class'); ?></td>
                    <td class="group"><?php echo $lecture->group; ?></td>
                    <td class="description">
                        <strong><?php echo $lecture->description; ?></strong><br />
                        <?php echo $lecture->lector; ?>
                    </td>
                    <td class="room"><?php echo $lecture->room; ?></td>
                    <td class="info"><?php echo $lecture->info; ?></td>
                </tr>
            <?php endforeach; ?>
        </table>

        <?php else: ?>
        <p>Keine Einträge.</p>
        <?php endif; ?>
    </div>

<?php endforeach; ?>

<?php if(!$this->ajax): ?>
</div>
<?php endif; ?>