<!DOCTYPE html>
<html>
<head>
    <meta name="language" content="de" />
    <meta charset="utf-8" />
    <title><?php echo $this->title ?> - FH Kufstein InfoScreen Webservice</title>
    <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl(); ?>/css/style.css" />
</head>
<body>
<div id="menu">
    <ul>
        <li id="menuBase"><a href="<?php echo $this->menuLink('day'); ?>">Infoscreen</a></li>
        <li id="menuWeek"><a href="<?php echo $this->menuLink('week'); ?>">Wochenübersicht</a></li>
    </ul>
</div>

<div class="container">
<?php echo $this->layout()->content; ?>

    <div id="footer" class="span-24">
        <div class="footermessage span-15">&nbsp;</div>
        <div class="footertext span-8 prepend-1 last">&copy; 2008-2010 <a href="http://ailoo.net/">Mathias Geat</a> (<a href="http://maff.ailoo.net/projects/fh-kufstein-raumbelegung-webservice/">Projektinfo</a>)</div>
    </div>
</div>
<div id="loading"></div>

<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/jquery.datepicker.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/jquery.tablesorter.min.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/infoscreen.js"></script>

<!--[if IE]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

<?php if ($this->config->services->analytics->enabled): ?>
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', '<?php echo $this->config->services->analytics->account; ?>']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
<?php endif; ?>

<?php if ($this->config->services->piwik->enabled): ?>
<script type="text/javascript">
var pkBaseURL = (("https:" == document.location.protocol) ? "https://<?php echo $this->config->services->piwik->baseurl; ?>" : "http://<?php echo $this->config->services->piwik->baseurl; ?>");
document.write(unescape("%3Cscript src='" + pkBaseURL + "piwik.js' type='text/javascript'%3E%3C/script%3E"));
</script><script type="text/javascript">
try {
var piwikTracker = Piwik.getTracker(pkBaseURL + "piwik.php", <?php echo $this->config->services->piwik->siteid; ?>);
piwikTracker.trackPageView();
piwikTracker.enableLinkTracking();
} catch( err ) {}
</script><noscript><p><img src="http://<?php echo $this->config->services->piwik->baseurl; ?>/piwik.php?idsite=<?php echo $this->config->services->piwik->siteid; ?>" style="border:0" alt="" /></p></noscript>
<?php endif; ?>

<?php if ($this->config->services->uservoice->enabled): ?>
<script type="text/javascript">
var uservoiceJsHost = ("https:" == document.location.protocol) ? "https://uservoice.com" : "http://cdn.uservoice.com";
document.write(unescape("%3Cscript src='" + uservoiceJsHost + "/javascripts/widgets/tab.js' type='text/javascript'%3E%3C/script%3E"))
</script>
<script type="text/javascript">
UserVoice.Tab.show({
  key: '<?php echo $this->config->services->uservoice->key; ?>',
  host: '<?php echo $this->config->services->uservoice->host; ?>',
  forum: 'general',
  alignment: 'left',
  background_color:'#3399FF',
  text_color: 'white',
  hover_color: '#333',
  lang: 'en'
})
</script>
<?php endif; ?>
</body>
</html>