<?php $this->title = 'InfoScreen SOAP API'; ?>

<section id="content">
    <h1><?php echo $this->title ?></h1>
    <p>Hi. I'm a <abbr title="Simple Object Access Protocol">SOAP</abbr> web service and I never learned how to deal with GET requests, so please feed me with correct data. For more information take a look at the <a href="/api/soap/wsdl"><abbr title="Web Service Description Language">WSDL</abbr></a> or visit the <a href="http://ailoo.net/projects/fh-kufstein-raumbelegung-webservice/">project page</a>.</p>
</section>