<?php
echo '<?xml version="1.0" encoding="UTF-8"?>' . "\n";
?>
<definitions xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" xmlns:tns="<?php echo $this->config->base_url ?>/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns="http://schemas.xmlsoap.org/wsdl/" targetNamespace="<?php echo $this->config->base_url ?>/">
    <types>
        <xsd:schema targetNamespace="<?php echo $this->config->base_url ?>/">
            <xsd:import namespace="http://schemas.xmlsoap.org/soap/encoding/" />
            <xsd:import namespace="http://schemas.xmlsoap.org/wsdl/" />
            <xsd:complexType name="Lecture">
                <xsd:all>
                    <xsd:element name="startTime" type="xsd:string"/>
                    <xsd:element name="endTime" type="xsd:string"/>
                    <xsd:element name="class" type="xsd:string"/>
                    <xsd:element name="description" type="xsd:string"/>
                    <xsd:element name="room" type="xsd:string"/>
                    <xsd:element name="lector" type="xsd:string"/>
                    <xsd:element name="info" type="xsd:string"/>
                </xsd:all>
            </xsd:complexType>
            <xsd:complexType name="Lectures">
                <xsd:complexContent>
                    <xsd:restriction base="SOAP-ENC:Array">
                        <xsd:attribute ref="SOAP-ENC:arrayType" wsdl:arrayType="tns:Lecture[]"/>
                    </xsd:restriction>
                </xsd:complexContent>
            </xsd:complexType>
            <xsd:complexType name="Filter">
                <xsd:all>
                    <xsd:element name="key" type="xsd:string"/>
                    <xsd:element name="value" type="xsd:string"/>
                </xsd:all>
            </xsd:complexType>
            <xsd:complexType name="Filters">
                <xsd:complexContent>
                    <xsd:restriction base="SOAP-ENC:Array">
                        <xsd:attribute ref="SOAP-ENC:arrayType" wsdl:arrayType="tns:Filter[]"/>
                    </xsd:restriction>
                </xsd:complexContent>
            </xsd:complexType>
            <xsd:complexType name="List">
                <xsd:complexContent>
                    <xsd:restriction base="SOAP-ENC:Array">
                        <xsd:attribute ref="SOAP-ENC:arrayType" wsdl:arrayType="xsd:string[]"/>
                    </xsd:restriction>
                </xsd:complexContent>
            </xsd:complexType>
        </xsd:schema>
    </types>
    <message name="getDayRequest">
        <part name="date" type="xsd:string" />
        <part name="filters" type="tns:Filters" />
    </message>
    <message name="getDayResponse">
        <part name="result" type="tns:Lectures" />
    </message>
    <message name="getListRequest">
        <part name="key" type="xsd:string" />
        <part name="selectfriendly" type="xsd:boolean" />
    </message>
    <message name="getListResponse">
        <part name="result" type="tns:List" />
    </message>
    <portType name="infoscreenPortType">
        <operation name="getDay">
            <input message="tns:getDayRequest" />
            <output message="tns:getDayResponse" />
        </operation>
        <operation name="getList">
            <input message="tns:getListRequest"/>
            <output message="tns:getListResponse"/>
        </operation>
    </portType>
    <binding name="infoscreenBinding" type="tns:infoscreenPortType">
        <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="getDay">
            <soap:operation soapAction="<?php echo $this->config->base_url ?>/api/soap/endpoint/getday" style="rpc"/>
            <input><soap:body use="encoded" namespace="<?php echo $this->config->base_url ?>/" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/></input>
            <output><soap:body use="encoded" namespace="<?php echo $this->config->base_url ?>/" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/></output>
        </operation>
        <operation name="getList">
            <soap:operation soapAction="<?php echo $this->config->base_url ?>/api/soap/endpoint/getlist" style="rpc"/>
            <input><soap:body use="encoded" namespace="<?php echo $this->config->base_url ?>/" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/></input>
            <output><soap:body use="encoded" namespace="<?php echo $this->config->base_url ?>/" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/></output>
        </operation>
    </binding>
    <service name="infoscreen">
        <port name="infoscreenPort" binding="tns:infoscreenBinding">
            <soap:address location="<?php echo $this->config->base_url ?>/api/soap/endpoint" />
        </port>
    </service>
</definitions>