<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" dir="ltr" lang="de-DE">
<head profile="http://gmpg.org/xfn/11">
    <title><?php echo $this->title ?> - FH Kufstein Raumbelegungs-Webservice</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	
    <script type="text/javascript">var base_url = "http://raumbelegung.stud.ailoo.net<?php echo $this->baseUrl(); ?>/"</script>
    <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/_res/js/jquery-1.2.6.min.js"></script> 
    <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/_res/js/jquery.datepicker.js"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/_res/js/jquery.tablesorter.min.js"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/_res/js/global.js"></script>
	
    <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl(); ?>/_res/css/style.css" />
</head>
<body>
    <div id="menu">
        <ul>
            <li><a href="/">Raumbelegung</a></li>
            <li><a href="/week">Wochenübersicht</a></li>
        </ul>
    </div>

    <div class="container">
	
<?php echo $this->layout()->content; ?>
    
		<div id="footer" class="span-24">
            <div class="footermessage span-15">&nbsp;</div>
			<div class="footertext span-8 prepend-1 last">&copy; 2008 <a href="http://ailoo.net/">Mathias Geat</a> (<a href="http://maff.ailoo.net/projects/fh-kufstein-raumbelegung-webservice/">Projektinfo</a>)</div>
		</div>
    
    </div>
    
    
    
    <div id="loading"></div>
    
</body>
</html>
